SELECT ii.ITEM_ID, ii.ITEM_NAME, ii.RARITY
FROM ITEM_INFO ii
WHERE ii.ITEM_ID NOT IN (
    SELECT DISTINCT it.ITEM_ID
    FROM ITEM_TREE it
    WHERE it.ITEM_ID IN 
    (SELECT DISTINCT PARENT_ITEM_ID FROM ITEM_TREE WHERE PARENT_ITEM_ID IS NOT NULL)
)
ORDER BY ii.ITEM_ID DESC;
