SELECT DISTINCT a.USER_ID, a.PRODUCT_ID
FROM ONLINE_SALE a
INNER JOIN (
    SELECT USER_ID, PRODUCT_ID
    FROM ONLINE_SALE
    GROUP BY USER_ID, PRODUCT_ID
    HAVING COUNT(*) > 1
) b ON a.USER_ID = b.USER_ID AND a.PRODUCT_ID = b.PRODUCT_ID
ORDER BY a.USER_ID ASC, a.PRODUCT_ID DESC;
