-- 코드를 입력하세요
SELECT  P.PRODUCT_CODE, (P.PRICE * O.SALES_AMOUNT) AS SALES
FROM PRODUCT AS P INNER JOIN
(
    SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS SALES_AMOUNT
    FROM OFFLINE_SALE
    GROUP BY PRODUCT_ID
) AS O
ON P.PRODUCT_ID = O.PRODUCT_ID
ORDER BY SALES DESC, P.PRODUCT_CODE ASC
;