-- 코드를 입력하세요
SELECT P.PRODUCT_ID, P.PRODUCT_NAME, P.PRICE * SUM(O.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT AS P JOIN FOOD_ORDER  AS O
ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE year(O.PRODUCE_DATE) = 2022 AND month(O.PRODUCE_DATE) = 5
GROUP BY P.PRODUCT_NAME
ORDER BY P.PRICE * SUM(O.AMOUNT) DESC, PRODUCT_ID ASC;
;