SELECT MEMBER_ID, MEMBER_NAME, GENDER, to_char(DATE_OF_BIRTH,'yyyy-mm-dd') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE GENDER = 'W' AND to_char(date_of_birth, 'mm') = 3 AND TLNO IS NOT NULL
ORDER BY MEMBER_ID ASC;