-- 코드를 입력하세요
SELECT B.CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK_SALES AS S LEFT JOIN BOOK AS B
ON S.BOOK_ID = B.BOOK_ID
WHERE year(S.SALES_DATE) = 2022 and month(S.SALES_DATE) = 1 
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY ASC
;